spring.application.name=Bus-Scheduling-and-RouteManagement-System
spring.datasource.url=jdbc:mysql://localhost:3306/busschedulingandroutemanagementsystem
server.port=8080
spring.datasource.username=root
spring.datasource.password=AjayKumar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
